export const FETCH = 'FETCH'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const SORT_BY_AUTHOR = 'SORT_BY_AUTHOR'
export const SORT_BY_TITLE = 'SORT_BY_TITLE'